### ISSUE TITLE
name collision on 'Action' with Flutter 1.7

### ISSUE THREAD

**Issue by r3flow** [RedBrogdon/rebloc#14]
rebloc-0.2.1/lib/src/widgets.dart:10:1: Error: 'Action' is imported from both 'package:flutter/src/widgets/actions.dart' and 'package:rebloc/src/engine.dart'

patch to fix this: https://github.com/iyatsouba/rebloc/commit/42b405a609550750505adcfcdbe618a51d504a52

**Comment by redbrogdon** [comment]
Interesting. I hadn't realized someone had gone to the trouble of forking the repo to get around the problem. Thanks for bringing it to my attention.

Rather than namespacing all the local stuff, I've solved the problem by hiding `Action` when importing `widgets.dart` from the framework.
