### ISSUE TITLE
initialState Async

### ISSUE THREAD

**Issue by gregorip02** [RedBrogdon/rebloc#17]
I have a usecase in my app and I need to load the initial state by querying the SharedPreferences package.

How can I make the initial state of my app asynchronous?

**Comment by redbrogdon** [comment]
I can think of a couple approaches, though these are off the top of my head.

One is that you could create an AppState class that contains a flag indicating whether the preferences have completed loading yet. Then your initial state would be a copy of that object with the flag set to false. You'd then create a Bloc to manage the loading and saving of data to shared preferences, and when the load was done it could update the state object with data and set the flag to true.

Another, hacky, way to do it would be to await the call to load shared preferences before calling runApp. :)
