### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by tenSunFree** [RedBrogdon/rebloc#20]
When I opened example, two errors occurred. Provide solutions for those in need.

First mistake, No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android.
![2020-07-23_193542](https://user-images.githubusercontent.com/23090085/88282237-b86a3280-cd1b-11ea-9ef6-82ac7b7a42dc.jpg)

Solution, go to the official website to download "Android NDK, Revision 16b", and then put the "mips64el-linux-android-4.9" in "Android\sdk\ndk-bundle".
https://developer.android.com/ndk/downloads/older_releases
![2020-07-23_194025](https://user-images.githubusercontent.com/23090085/88282566-637aec00-cd1c-11ea-9441-bf8397135f94.jpg)

Second mistake, Failed to execute aapt.
![2020-07-23_193838](https://user-images.githubusercontent.com/23090085/88282418-1f87e700-cd1c-11ea-92d9-79e84262664d.jpg)

Solution, in "android/app/build.gradle", modify "compileSdkVersion" to 28.
![2020-07-23_194123](https://user-images.githubusercontent.com/23090085/88282787-c53b5600-cd1c-11ea-8a52-802cd9c76955.jpg)

**Comment by redbrogdon** [comment]
I'm not able to reproduce this issue. Is it still a problem?

**Comment by tenSunFree** [comment]
The problem has been solved, thank you.
