### ISSUE TITLE
Any example rebloc and firebase

### ISSUE THREAD

**Issue by ghost** [RedBrogdon/rebloc#3]
I think this plugin is so brilliant and make state management much easier!
Thank you so much. 
However I would like to know how to update UI when `Firestore` data changed or created in this plugin. For instance, when you put a new item in shopping cart,  cart icon's number updates like flutter talk in IO. Since bloc attached to this plugin, I think I should put login in there but I'm not  sure how to do it. Could you give an example?
Again thank you for great plugin.

**Comment by redbrogdon** [comment]
Interesting point. I haven't really looked at how Firebase and rebloc could work together yet.

One of the nice things about the Firebase plugin for Flutter, though, is that it provides data in the form of Dart streams, which should blend nicely with rebloc's dispatch stream. See this line in the official example for an idea of what I mean:

https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/lib/main.dart#L35

One way to handle integrating Firebase would be to create a class called FirebaseCartBloc<AppState> that handled setting up the connection to Firebase, and then emitted an action to the middleware stream any time a new value came out of the stream provided by Firebase. That Bloc could also contain a reducer that processed the action and updated your app state object with the new data, which would then get emitted by the `states` stream where your widgets could get it.

At the moment I'm completely focused on the Voxxed Days app (https://github.com/redbrogdon/voxxedapp), and don't have time to work on a Firebase example. I'll put it on my todo list, though. If someone reading this creates one, of course, I'm only too happy to direct people to it from this repo!

**Comment by ghost** [comment]
Sorry for late response. 
Ok I try to figure it out somehow!
Again thank you for your great work!
 
sincerely,

**Comment by jogboms** [comment]
@TJ543 in the case you still need one, i addressed it #13
