### ISSUE TITLE
How dispose resources of bloc

### ISSUE THREAD

**Issue by mrdaios** [RedBrogdon/rebloc#5]

**Comment by redbrogdon** [comment]
This is an interesting question. So far, the way I have been using Rebloc is to set the blocs and store up at the beginning, and then leave them in place the entire time the app is running. I don't want that to be a requirement, though. Ideally, apps should be able to use multiple stores, and create/destroy them on the fly.

Dart doesn't offer finalizers, so I'd have to add something to the API specifically for this, similar to the way you're expected to call `close` on a StreamController.

Does anyone have opinions about simply adding a `dispose` method to the `Store` and `Bloc` classes?

**Comment by ThinkDigitalSoftware** [comment]
> Does anyone have opinions about simply adding a `dispose` method to the `Store` and `Bloc` classes?
That's a great idea!

**Comment by redbrogdon** [comment]
This has been added in the new version, 0.3.0.
