### ISSUE TITLE
Documentation typo in pub.dartlang.org

### ISSUE THREAD

**Issue by me7** [RedBrogdon/rebloc#6]
First of all, thank you @RedBrogdon for create such a good library. I very appriciate it.
(Also a lot of good episodes on boring flutter that I love to watch)

But one thing I want to mention is the readme document on https://pub.dartlang.org/packages/rebloc#-readme-tab- have a typo

I saw that you've fixed it in your commit but it's not propogate to pub.dartlang.org yet.
Could you help correct it? (for a good impression of new comer)

Cheer!!
![image](https://user-images.githubusercontent.com/10399270/48925552-65612c00-eef7-11e8-8a1a-4f5d3249b37c.png)

**Comment by redbrogdon** [comment]
I've been struggling with the test script for the library, and didn't feel comfortable pushing a new version until I had it under control. It's fixed now, though, and v0.2.1 is available with a corrected README.

Thanks for reading the docs all the way through. 😄 

I hope the library is useful for you, though please bear in mind that it's still an experiment!
