### ISSUE TITLE
Invalid override?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [RedBrogdon/rebloc#7]
Given the following code:

_Default override fill in code:_
```dart
@override
  FutureOr<Action> middleware(DispatchFunction dispatcher, ExpandingCardState state, Action action) {
    // TODO: implement middleware
    return super.middleware(dispatcher, state, action);
  }
```
or _Modified to return action explicitly_
```dart
class ConstraintBloc extends SimpleBloc<ExpandingCardState> {
  @override
  FutureOr<Action> middleware(DispatchFunction dispatcher, ExpandingCardState state, Action action) {
    // TODO: implement middleware
    return action;
  }
}
```
Why do I get the following analysis error?
>'ConstraintBloc.middleware' ('((Action) → void, ExpandingCardState, Action) → dynamic') isn't a valid override of 'SimpleBloc.middleware' ('((Action) → void,

**Comment by ThinkDigitalSoftware** [comment]
It's satisfied if I change the function to an Action return type in the signature.

**Comment by redbrogdon** [comment]
Are you importing `dart:async` at the top of the file? I've found that the analyzer will give an error very similar to the one you're describing if it's missing.

**Comment by ThinkDigitalSoftware** [comment]
I was not

**Comment by redbrogdon** [comment]
Did that fix the issue?

This might be something for me to bring up with the tools team. Without the import, it interprets `FutureOr<Action>` as a `dynamic`, and gives you an error about the return type not matching. It's correct to do so, but the *real* error is that you're missing the import that provides `FutureOr<>`.

**Comment by ThinkDigitalSoftware** [comment]
(-_-) yes, that did fix the issue ,thank you . The tools team would be on jet brains.com?

**Comment by redbrogdon** [comment]
It's actually our team that works on the tools, so I've referenced this issue in one that already exists for the plugin. Thanks for filing a bug -- let me know if you run into any other problems!

**Comment by ThinkDigitalSoftware** [comment]
No problem. I'm promoting  rebloc wherever I can! I love it. Thank you as
well. We really need a video on it.
